nginx:
  restart: always
  build: nginx
  ports:
    - "80:80"
  links:
    - repo
    - ui

repo:
  restart: always
  build: repo
  ports:
    - "5000:5000"

ui:
  restart: always
  image: hyper/docker-registry-web
  ports:
    - "8080:8080"
  links:
    - repo:docker.orctom.com
  environment:
    - REGISTRY_HOST=docker.orctom.com
