elasticsearch:
  image: orctom/elasticsearch:2.2.0
  ports: 
    - "9200:9200"
    - "9300:9300"

logstash:
  image: logstash

kibana:
  image: orctom/kibana:4.4.1
  ports:
    - "5601:5601"
  links:
    - elasticsearch