FROM orctom/hadoop:latest
MAINTAINER Hao Chen <orctom@gmail.com>

ADD hadoop-env.sh $HADOOP_CONF_DIR/hadoop-env.sh
ADD core-site.xml $HADOOP_CONF_DIR/core-site.xml
ADD hdfs-site.xml $HADOOP_CONF_DIR/hdfs-site.xml
ADD yarn-site.xml $HADOOP_CONF_DIR/yarn-site.xml
ADD mapred-site.xml $HADOOP_CONF_DIR/mapred-site.xml
